#pragma once
#define EXPORT_VAR __declspec(dllexport) extern
#define EXPORT_FUNC __declspec(dllexport)
// Standard C++ includes
#include <algorithm>
#include <chrono>
#include <iostream>
#include <random>

// Standard C includes
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <intrin.h>

int inline gennCLZ(unsigned int value) {
    unsigned long leadingZero = 0;
    if( _BitScanReverse(&leadingZero, value)) {
        return 31 - leadingZero;
    }
    else {
        return 32;
    }
}

using std::min;
using std::max;
#define SCALAR_MIN 1.175494351e-38f
#define SCALAR_MAX 3.402823466e+38f
#define TIME_MIN 1.175494351e-38f
#define TIME_MAX 3.402823466e+38f
extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// Runner functions
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC void stepTime(unsigned long long timestep, unsigned long long numRecordingTimesteps);

// Functions generated by backend
EXPORT_FUNC void updateNeurons(float t, unsigned int recordingTimestep); 
EXPORT_FUNC void updateSynapses(float t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
EXPORT_FUNC void initializeHost();

// Merged group upload functions
EXPORT_FUNC void pushMergedNeuronInitGroup0ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0);
EXPORT_FUNC void pushMergedNeuronInitGroup1ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronInitGroup2ToDevice(unsigned int idx, float* RefracTime, float* V, float* outPostInSyn0, float* outPostInSyn1, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedSynapseSparseInitGroup0ToDevice(unsigned int idx, float* g, uint32_t* rowLength, uint32_t numSrcNeurons, uint32_t rowStride);
EXPORT_FUNC void pushMergedNeuronUpdateGroup0ToDevice(unsigned int idx, float* RefracTime, float* V, float* outPostInSyn0, float* outPostInSyn1, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedNeuronUpdateGroup1ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0, uint32_t* recordSpk);
EXPORT_FUNC void pushMergedNeuronUpdateGroup2ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronUpdateGroup3ToDevice(unsigned int idx, float* RefracTime, float* V, float* outPostInSyn0, float* outPostInSyn1, uint32_t* recordSpk, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedPresynapticUpdateGroup0ToDevice(unsigned int idx, float* g, uint32_t* ind, float* outPost, uint32_t* rowLength, uint32_t* srcSpk, uint32_t* srcSpkCnt, uint32_t rowStride);
EXPORT_FUNC void pushMergedNeuronSpikeQueueUpdateGroup0ToDevice(unsigned int idx, uint32_t* spkCntSynSpike0);
}  // extern "C"
