#pragma once
#define EXPORT_VAR __declspec(dllexport) extern
#define EXPORT_FUNC __declspec(dllexport)
// Standard C++ includes
#include <algorithm>
#include <chrono>
#include <iostream>
#include <random>

// Standard C includes
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <intrin.h>

int inline gennCLZ(unsigned int value) {
    unsigned long leadingZero = 0;
    if( _BitScanReverse(&leadingZero, value)) {
        return 31 - leadingZero;
    }
    else {
        return 32;
    }
}

using std::min;
using std::max;
#define SCALAR_MIN 1.175494351e-38f
#define SCALAR_MAX 3.402823466e+38f
#define TIME_MIN 1.175494351e-38f
#define TIME_MAX 3.402823466e+38f
extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------
extern std::mt19937 hostRNG;
extern std::uniform_real_distribution<float> standardUniformDistribution;
extern std::normal_distribution<float> standardNormalDistribution;
extern std::exponential_distribution<float> standardExponentialDistribution;


// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// Runner functions
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC void stepTime(unsigned long long timestep, unsigned long long numRecordingTimesteps);

// Functions generated by backend
EXPORT_FUNC void updateNeurons(float t, unsigned int recordingTimestep); 
EXPORT_FUNC void updateSynapses(float t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
EXPORT_FUNC void initializeHost();

// Merged group upload functions
EXPORT_FUNC void pushMergedNeuronInitGroup0ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* rPreOutSynWUMPre0);
EXPORT_FUNC void pushMergedNeuronInitGroup1ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0, float* outPostInSyn1, float* outPostInSyn2, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedNeuronInitGroup2ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* denDelayInSyn5, uint32_t* denDelayPtrInSyn5, float* outPostInSyn0, float* outPostInSyn1, float* outPostInSyn2, float* outPostInSyn3, float* outPostInSyn4, float* outPostInSyn5, float* rPostInSynWUMPost0, float* rPostInSynWUMPost1, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedNeuronInitGroup3ToDevice(unsigned int idx, float* firingRate, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronInitGroup4ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronInitGroup5ToDevice(unsigned int idx, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedSynapseInitGroup0ToDevice(unsigned int idx, float* g);
EXPORT_FUNC void pushMergedSynapseConnectivityInitGroup0ToDevice(unsigned int idx, uint32_t* ind, uint32_t* rowLength);
EXPORT_FUNC void pushMergedSynapseSparseInitGroup0ToDevice(unsigned int idx, uint32_t* colLength, float* g, uint32_t* ind, uint32_t* remap, uint32_t* rowLength, float constantg);
EXPORT_FUNC void pushMergedSynapseSparseInitGroup1ToDevice(unsigned int idx, float* g, uint32_t* rowLength);
EXPORT_FUNC void pushMergedNeuronUpdateGroup0ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0, float* outPostInSyn1, float* outPostInSyn2, uint32_t* recordSpk, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedNeuronUpdateGroup1ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* rPreOutSynWUMPre0);
EXPORT_FUNC void pushMergedNeuronUpdateGroup2ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* outPostInSyn0, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, float TauInh, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronUpdateGroup3ToDevice(unsigned int idx, uint32_t* endSpike, float* spikeTimes, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t* startSpike);
EXPORT_FUNC void pushMergedNeuronUpdate3spikeTimesToDevice(unsigned int idx, float* value);
EXPORT_FUNC void pushMergedNeuronUpdateGroup4ToDevice(unsigned int idx, float* firingRate, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0, uint32_t numNeurons);
EXPORT_FUNC void pushMergedNeuronUpdateGroup5ToDevice(unsigned int idx, float* Iext, float* Iinh, float* RefracTime, float* V, float* denDelayInSyn5, uint32_t* denDelayPtrInSyn5, float* outPostInSyn0, float* outPostInSyn1, float* outPostInSyn2, float* outPostInSyn3, float* outPostInSyn4, float* outPostInSyn5, float* rPostInSynWUMPost0, float* rPostInSynWUMPost1, uint32_t* recordSpk, uint32_t* spkCntSynSpike0, uint32_t* spkSynSpike0);
EXPORT_FUNC void pushMergedPresynapticUpdateGroup0ToDevice(unsigned int idx, float* g, uint32_t* ind, float* outPost, uint32_t* rowLength, uint32_t* srcSpk, uint32_t* srcSpkCnt, uint32_t rowStride);
EXPORT_FUNC void pushMergedPresynapticUpdateGroup1ToDevice(unsigned int idx, float* g, float* outPost, uint32_t* srcSpk, uint32_t* srcSpkCnt, uint32_t numTrgNeurons);
EXPORT_FUNC void pushMergedPresynapticUpdateGroup2ToDevice(unsigned int idx, uint8_t* d, float* denDelay, uint32_t* denDelayPtr, float* g, uint32_t* ind, uint32_t* rowLength, uint32_t* srcSpk, uint32_t* srcSpkCnt);
EXPORT_FUNC void pushMergedPresynapticUpdateGroup3ToDevice(unsigned int idx, uint32_t* ind, float* outPost, uint32_t* rowLength, uint32_t* srcSpk, uint32_t* srcSpkCnt);
EXPORT_FUNC void pushMergedPostsynapticUpdateGroup0ToDevice(unsigned int idx, uint32_t* colLength, float* g, float* rPost, float* rPre, uint32_t* remap, uint32_t* trgSpk, uint32_t* trgSpkCnt);
EXPORT_FUNC void pushMergedNeuronSpikeQueueUpdateGroup0ToDevice(unsigned int idx, uint32_t* spkCntSynSpike0);
EXPORT_FUNC void pushMergedSynapseDendriticDelayUpdateGroup0ToDevice(unsigned int idx, uint32_t* denDelayPtr);
}  // extern "C"
